# Generated by Django 4.2.1 on 2023-10-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_remove_competition_questions_competition_trivia_set"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trivia",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="trivia",
            name="question",
            field=models.TextField(unique=True),
        ),
    ]
