# Generated by Django 4.2.1 on 2023-11-01 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_trivia_question_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="end_time",
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name="competition",
            name="ended",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="competition",
            name="started",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="competition",
            name="started_at",
            field=models.DateTimeField(default=None),
        ),
        migrations.CreateModel(
            name="SeenCompetitionTrivia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.competition",
                    ),
                ),
                (
                    "trivia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.trivia"
                    ),
                ),
            ],
        ),
    ]
