# Generated by Django 4.2.1 on 2023-11-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_competition_end_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="created_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="competition",
            name="started_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
