# Generated by Django 4.2.1 on 2023-11-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_competition_created_at_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="competitiontrivia",
            constraint=models.UniqueConstraint(
                fields=("competition", "trivia"), name="unique_competition_trivia"
            ),
        ),
        migrations.AddConstraint(
            model_name="seencompetitiontrivia",
            constraint=models.UniqueConstraint(
                fields=("competition", "trivia"), name="unique_seen_competition_trivia"
            ),
        ),
    ]
